#!/usr/bin/python 

import os
import sys
import re
from numpy import array

def get_mean_accuracy(log_path):
# Extracts mean accuracy from the log file
	log_file = open(log_path, "r")
	lines = log_file.readlines()
	log_file.close()

	scores = list()
	for line in lines:
		line_model = ""
		accuracy_match = re.search("Accuracy\s*=\s*(\d+\.\d+)", line)
		if accuracy_match:
			scores.append(float(accuracy_match.group(1)))
			
	print "Items = ",len(scores), ", Mean = ", array(scores).mean(), ", Std = ", array(scores).std()

def clean_text(line):
    skip_line =	(
		    re.search("^unicode", line,re.IGNORECASE) or
		    re.search("^lemmatiz", line,re.IGNORECASE) or
		    re.search("^script has", line,re.IGNORECASE) or
		    re.search("^\n", line,re.IGNORECASE) or
		    re.search("^\[", line,re.IGNORECASE) or
		    re.search(r"^/home/", line,re.IGNORECASE) or
		    re.search(r"tokens were lemmatized", line,re.IGNORECASE) or 
		    re.search(r"optimization finished", line,re.IGNORECASE) or 
		    re.search(r"objective value", line,re.IGNORECASE) or 
		    re.search(r"nsv = ", line,re.IGNORECASE) or 
		    re.search(r"\.\*", line,re.IGNORECASE) or
		    re.search(r"^\s*\d+\s*$", line,re.IGNORECASE) or
		    re.search(r"^\s*$", line,re.IGNORECASE) or 
		    re.search("^features", line,re.IGNORECASE)
		    ) 
    if skip_line:
	    return ""
    else:
	    line = re.sub(r"(Accuracy.+)", r"\1\n", line)
	    return line

#####################################
# Entry point
#####################################

ACCURACY = True

#Process parameters
PARAM_NUM = 1
if len(sys.argv) < PARAM_NUM + 1:
    print "Expected", PARAM_NUM, "parameters but was", str(len(sys.argv)-1)
    print "This script cleans up the log file generated by 'classify-all.sh' script"
    print "Usage:", sys.argv[0], "<log-file>"
    print "<log-file>\tLog of 'classify-all.sh' script."
    sys.exit()

log_fpath = sys.argv[1]

# Clean the text
log_file = open(log_fpath, "r")
output_file = open(log_fpath + ".txt", "w")
for line in log_file: 
    output_file.write(clean_text(line))
log_file.close()
output_file.close()
os.remove(log_fpath)
os.rename(log_fpath + ".txt", log_fpath)

get_mean_accuracy(log_fpath)

print "Script has finished successfully."
